name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/friday
            # Скачиваем новые данные, не пытаясь их склеить с локальными
            git fetch origin main
            # Жестко затираем локальные файлы версией с GitHub
            git reset --hard origin/main
            
            source myenv/bin/activate
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            systemctl restart friday-ws.service
            systemctl restart friday-http.service